name: "Terraform Destroy"
on:
 workflow_dispatch:

env:
  TF_CLOUD_ORGANIZATION: "subhamay-cloudworks"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "0055-borage-tf"
  CONFIG_DIRECTORY: "./"

jobs:
    terraform:
      name: "Terraform Destroy"
      runs-on: ubuntu-latest
      permissions:
        contents: read
      steps:
        - name: Checkout
          uses: actions/checkout@v3
  
        - name: Terraform Init
          id: init
          run: terraform init
          continue-on-error: false

        - name: Upload Configuration
          uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
          id: apply-upload
          with:
            workspace: ${{ env.TF_WORKSPACE }}
            directory: ${{ env.CONFIG_DIRECTORY }}

        - name: Show Destroy Plan
          id: show-destroy-plan
          run: terraform plan -destroy
          continue-on-error: true
    
        - name: Destroy
          id: destroy
          run: terraform destroy -auto-approve
    
