name: "Terraform Destroy"
on:
 workflow_dispatch:

jobs:
    terraform:
        name: "Terraform Destroy"
        runs-on: ubuntu-latest
        steps:
            - name: Show Destroy Plan
              id: show-destroy-plan
              run: terraform plan -destroy
              continue-on-error: true
    
            - name: Destroy
              id: destroy
              run: terraform destroy -auto-approve
    
